pub const ALL_FONTS: &[&str] = &[
    "Al Bayan",
    "Al Nile",
    "Al Tarikh",
    "American Typewriter",
    "Andale Mono",
    "Apple Braille",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "Arial Black",
    "Arial Hebrew",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Arial",
    "Avenir Next Condensed",
    "Avenir Next",
    "Avenir",
    "Ayuthaya",
    "Baghdad",
    "Bangla MN",
    "Bangla Sangam MN",
    "Baskerville",
    "Beirut",
    "Big Caslon",
    "Bodoni Ornaments",
    "Bradley Hand",
    "Brush Script MT",
    "Chalkboard SE",
    "Chalkboard",
    "Chalkduster",
    "Cochin",
    "Comic Sans MS",
    "Copperplate",
    "Corsiva Hebrew",
    "Courier New",
    "Courier",
    "Damascus",
    "DecoType Naskh",
    "Devanagari MT",
    "Devanagari Sangam MN",
    "Didot",
    "Diwan Kufi",
    "Diwan Thuluth",
    "Euphemia UCAS",
    "Farah",
    "Farisi",
    "Futura",
    "GB18030 Bitmap",
    "Geeza Pro",
    "Geneva",
    "Georgia",
    "Gill Sans",
    "Gujarati MT",
    "Gujarati Sangam MN",
    "Gurmukhi MN",
    "Gurmukhi MT",
    "Gurmukhi Sangam MN",
    "Heiti SC",
    "Helvetica Neue",
    "Helvetica",
    "Herculanum",
    "Hiragino Sans GB",
    "Hiragino Sans",
    "Hoefler Text",
    "ITF Devanagari",
    "Impact",
    "InaiMathi",
    "Kannada MN",
    "Kefa",
    "Khmer MN",
    "Khmer Sangam MN",
    "Kohinoor Bangla",
    "Kohinoor Telugu",
    "Kokonor",
    "Krungthep",
    "KufiStandardGK",
    "Lao MN",
    "Lao Sangam MN",
    "Lucida Grande",
    "Luminari",
    "Marker Felt",
    "Menlo",
    "Microsoft Sans Serif",
    "Mishafi Gold",
    "Monaco",
    "Mshtakan",
    "Muna",
    "Nadeem",
    "New Peninim MT",
    "Noteworthy",
    "Optima",
    "Oriya Sangam MN",
    "PT Mono",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Sans",
    "PT Serif Caption",
    "PT Serif",
    "Palatino",
    "Papyrus",
    "Phosphate",
    "PingFang HK",
    "Plantagenet Cherokee",
    "Raanana",
    "STIXGeneral",
    "STIXIntegralsD",
    "STIXIntegralsSm",
    "STIXIntegralsUp",
    "STIXIntegralsUpD",
    "STIXIntegralsUpSm",
    "STIXSizeFiveSym",
    "STIXSizeFourSym",
    "STIXSizeOneSym",
    "STIXSizeThreeSym",
    "STIXSizeTwoSym",
    "STIXVariants",
    "STSong",
    "Sana",
    "Sathu",
    "Savoye LET",
    "SignPainter",
    "Silom",
    "Sinhala Sangam MN",
    "Skia",
    "Snell Roundhand",
    "Songti SC",
    "Sukhumvit Set",
    "Symbol",
    "Tahoma",
    "Tamil Sangam MN",
    "Telugu Sangam MN",
    "Thonburi",
    "Times New Roman",
    "Trattatello",
    "Trebuchet MS",
    "Verdana",
    "Waseem",
    "Zapfino",
    "Charter",
    "DIN Alternate",
    "DIN Condensed",
    "Noto Nastaliq Urdu",
    "Rockwell",
    "Zapf Dingbats",
    "BlinkMacSystemFont",
    "Mishafi",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Oriya MN",
    "Songti TC",
    "Tamil MN",
    "Telugu MN",
    "Webdings",
    "Wingdings",
    "Copperplate Gothic Bold",
    "Andale Mono",
    "Noto Sans Brahmi",
    "Fixedsys Regular",
    "Hiragino Mincho ProN W6",
    "System",
    "Castellar",
    "Noto Sans Old Italic",
    "STIXSizeThreeSym-Regular",
    "system-ui",
    "Malgun Gothic Semilight",
    "KacstOne",
    "Bodoni 72 Oldstyle",
    "Avenir Next Condensed Heavy",
    "Noto Sans CJK SC",
    "Proxy 4",
    "Hiragino Kaku Gothic StdN",
    "URW Gothic",
    "MingLiU_HKSCS-ExtB Regular",
    "Noto Sans Limbu",
    "STIXGeneral",
    "Keraleeyam",
    "Lao Sangam MN",
    "Sawasdee",
    "Tibetan Machine Uni",
    "Niagara Solid",
    "STIXSizeTwoSym-Regular",
    "Corbel Light",
    "Waree",
    "STIXGeneral-Regular",
    "Microsoft Uighur",
    "Noto Sans CJK HK",
    "Sahadeva",
    "Noto Sans Lisu",
    "Gargi",
    "padmaa",
    "Ubuntu Thin",
    "default",
    "Kailasa",
    "Noto Sans Lepcha",
    "Noto Sans Meroitic",
    "KacstScreen",
    "Matura MT Script Capitals",
    "Farisi",
    "SimSun-ExtB",
    "Seravek ExtraLight",
    "Beirut",
    "Myanmar MN",
    "MS PGothic",
    "Noto Sans Mono CJK TC",
    "AquaKana",
    "Avenir Light",
    "Hiragino Sans W1",
    "KacstDigital",
    "Noto Sans Duployan",
    "Hoefler Text Ornaments",
    "Noto Sans Nabataean",
    "Microsoft Sans Serif Regular",
    "Hiragino Kaku Gothic Pro",
    "Noto Sans Mono CJK KR",
    "KufiStandardGK",
    "ITF Devanagari Marathi",
    "STIXSizeThreeSym",
    "Sitka Banner",
    "Snap ITC",
    "Noto Sans Mahajani",
    "Papyrus",
    "STIXGeneral-BoldItalic",
    "Noto Sans Caucasian Albanian",
    "MS UI Gothic",
    "Noto Sans Kannada",
    "Palatino Linotype",
    "Bookshelf Symbol 7",
    "Big Caslon",
    "Hiragino Sans W0",
    "Noto Serif Ahom",
    "GOTHAM",
    "Ani",
    "Franklin Gothic Book",
    "Noto Sans Glagolitic",
    "Chalkboard",
    "MingLiU_HKSCS-ExtB",
    "Kinnari",
    "Small Fonts Regular",
    "KacstQurn",
    "STIXIntegralsUpD-Regular",
    "Noto Sans Multani",
    "Helvetica",
    "Tamil MN",
    "STIXSizeFiveSym",
    "FreeSerif",
    "Hiragino Sans W5",
    "Impact Regular",
    "Ubuntu",
    "Copperplate Gothic",
    "Noto Sans Mono CJK HK",
    "Lao MN",
    "FangSong",
    "Kefa",
    "Noto Sans Old Hungarian",
    "Arial Black",
    "Suruma",
    "Parchment",
    "Bahnschrift",
    "Calibri Light",
    "BankGothic Md BT",
    "Noto Sans Saurashtra",
    "Arial Hebrew",
    "Likhan",
    "Haettenschweiler",
    "Lohit Devanagari",
    "Avenir Next Condensed",
    "Noto Sans Kharoshthi",
    "Peddana",
    "Segoe UI Emoji",
    "Lohit Gurmukhi",
    "ITF Devanagari",
    "Comic Sans MS",
    "Gloucester MT Extra Condensed",
    "Nimbus Roman",
    "Padauk Book",
    "serif",
    "Mallanna",
    "Yrsa Medium",
    "-apple-system",
    "Kannada MN",
    "Arial Hebrew Scholar",
    "Felix Titling",
    "Ebrima",
    "Gabriola",
    "STIXIntegralsUpD",
    "Noto Sans Ol Chiki",
    "Noto Sans Tagalog",
    "Hiragino Maru Gothic ProN",
    "Gill Sans MT Condensed",
    "Showcard Gothic",
    "Hiragino Kaku Gothic StdN W8",
    "AnjaliOldLipi",
    "Khmer MN",
    "Karumbi",
    "Bahnschrift Light",
    "Baskerville",
    "STIXNonUnicode-Regular",
    "STIXGeneral-Italic",
    "Noto Sans Cypriot",
    "AvantGarde Bk BT",
    "Krungthep",
    "Charter Black",
    "Yrsa Light",
    "Hiragino Sans W2",
    "MS Gothic Regular",
    "Modern Regular",
    "Ramaraja",
    "Yu Gothic UI",
    "Vemana2000",
    "TTCommons",
    "Footlight MT Light",
    "Lohit Telugu",
    "Imprint MT Shadow",
    "Phosphate",
    "Microsoft Himalaya Regular",
    "Apple Braille Pinpoint 8 Dot",
    "Hiragino Mincho ProN",
    "Samanata",
    "Yu Gothic Regular",
    "KacstTitleL",
    "Noto Sans Tagbanwa",
    "MS UI Gothic Regular",
    "Noto Sans Imperial Aramaic",
    "Plantagenet Cherokee",
    "Hiragino Mincho Pro W3",
    "Noto Sans Batak",
    "Heiti SC",
    "Savoye LET",
    "Segoe UI Black",
    "ori1Uni",
    "Meiryo UI",
    "RaghuMalayalamSans",
    "Songti TC",
    "Georgia",
    "Mistral",
    "ARNO PRO",
    "Pagul",
    "STIXIntegralsSm-Regular",
    "KacstArt",
    "Tamil Sangam MN",
    "Noto Sans Hanunoo",
    "Shree Devanagari 714 Bold",
    "Lohit Gujarati",
    "Noto Sans Psalter Pahlavi",
    "Agency FB",
    "Rekha",
    "Bookman Old Style",
    "Microsoft YaHei UI",
    "Roboto",
    "MS Serif",
    "Symbol Regular",
    "Thonburi",
    "Noto Sans Bhaiksuki",
    "Songti SC",
    "NSimSun",
    "Yu Gothic Medium",
    "Gujarati MT",
    "Noto Sans Bassa Vah",
    "Lucida Console Regular",
    "Rasa",
    "Apple SD Gothic Neo",
    "Noto Sans Warang Citi",
    "Noto Sans Ogham",
    "Yrsa",
    "Jamrul",
    "Bell MT",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsD",
    "D050000L",
    "Noto Sans Hatran",
    "American Typewriter",
    "Dyuthi",
    "Al Bayan",
    "Corbel",
    "Fixedsys",
    "Tlwg Typewriter",
    "Nimbus Mono PS",
    "Clarendon",
    "ZWAdobeF",
    "Kalapi",
    "Avenir Book",
    "Ubuntu Light",
    "Lohit Malayalam",
    "STIXSizeFourSym",
    "Rockwell",
    "Noto Sans",
    "Sukhumvit Set",
    "Microsoft Himalaya",
    "Iowan Old Style",
    "DengXian Light",
    "Hiragino Sans W4",
    "Monotype Corsiva",
    "Noto Serif CJK TC",
    "Noto Sans Chakma",
    "Roman",
    "Trattatello",
    "InaiMathi",
    "Seravek Light",
    "Noto Sans Mandaic",
    "Vladimir Script",
    "Phetsarath OT",
    "Noto Sans Newa",
    "Curlz MT",
    "Malayalam MN",
    "Gurmukhi Sangam MN",
    "MS Reference Specialty",
    "Minion Pro",
    "Geeza Pro",
    "Gill Sans Ultra Bold",
    "Hiragino Maru Gothic Pro W4",
    "Hiragino Kaku Gothic ProN W6",
    "Cooper Black",
    "Century Gothic",
    "Galvji",
    "Shree Devanagari 714",
    "Bauhaus 93",
    "DIN Alternate",
    "Noto Sans Old Permic",
    "Lucida Bright",
    "SignPainter",
    "Kohinoor Telugu",
    "Staccato222 BT",
    "Calibri",
    "Lohit Kannada",
    "Noto Sans Manichaean",
    "Nimbus Sans",
    "Lohit Bengali",
    "Noto Sans Osage",
    "STIXSizeTwoSym-Bold",
    "Verdana",
    "Hiragino Kaku Gothic ProN",
    "AR PL UMing TW MBE",
    "Baghdad",
    "Bangla MN",
    "Avenir Next Ultra Light",
    "STIXIntegralsSm",
    "Samyak Gujarati",
    "PingFang SC",
    "Kohinoor Devanagari",
    "Noto Sans Vai",
    "Noto Sans Old Persian",
    "Forte",
    "Microsoft Yi Baiti",
    "Noto Serif",
    "SimSun",
    "Microsoft JhengHei UI Light",
    "HoloLens MDL2 Assets",
    "Party LET",
    "Hiragino Mincho Pro",
    "Avenir Next Medium",
    "STSong",
    "Maiandra GD",
    "Gujarati Sangam MN",
    "Gill Sans MT",
    "Poor Richard",
    "Apple Braille Pinpoint 6 Dot",
    "Noto Sans Shavian",
    "Noto Sans Egyptian Hieroglyphs",
    "Oriya Sangam MN",
    "Arabic Typesetting",
    "Noto Sans Gothic",
    "Damascus",
    "Hiragino Maru Gothic Pro",
    "Leelawadee UI",
    "Academy Engraved LET",
    "Book Antiqua",
    "Segoe UI",
    "Noto Sans Cuneiform",
    "Informal Roman",
    "fantasy",
    "Purisa",
    "Avenir Next Demi Bold",
    "Nimarla UI",
    "Rasa Medium",
    "Bangla Sangam MN",
    "STIXIntegralsUpD-Bold",
    "Zapf Dingbats",
    "Snell Roundhand",
    "KacstPoster",
    "STIXIntegralsUpSm",
    "Al Nile",
    "Times LT MM",
    "Proxy 7",
    "Proxy 5",
    "BlinkMacSystemFont",
    "Leelawadee",
    "Noto Sans Lydian",
    "AR PL UKai TW",
    "KaiTi",
    "Mandali",
    "Samyak Tamil",
    "Hiragino Kaku Gothic Pro W6",
    "Noto Color Emoji",
    "Silom",
    "Telugu Sangam MN",
    "Noto Sans Mro",
    "Sylfaen",
    "NSimSun Regular",
    "Diwan Kufi",
    "Futura",
    "KacstNaskh",
    "MS Reference Sans Serif",
    "Avenir Heavy",
    "Noto Sans Phoenician",
    "PT Sans Narrow",
    "Noto Sans Tai Le",
    "Goudy Old Style",
    "Berlin Sans FB",
    "News Gothic MT",
    "Keyboard",
    "Papyrus Condensed",
    "Noteworthy",
    "PT Sans Caption",
    "Marker Felt",
    "Google Sans",
    "DejaVu Sans Mono",
    "Geneva",
    "Letter Gothic",
    "Century",
    "MingLiu-ExtB Regular",
    "Candara Light",
    "Samyak Devanagari",
    "Segoe UI Emoji Regular",
    "Noto Sans Javanese",
    "Kannada Sangam MN",
    "PMingLiU-ExtB Regular",
    "Chandas",
    "Franklin Gothic",
    "STIXIntegralsUp",
    "Noto Sans Sora Sompeng",
    "Liberation Sans Narrow",
    "STIXSizeFiveSym-Regular",
    "Helvetica LT MM",
    "Microsoft YaHei Light",
    "Shree Devanagari 714 Bold Italic",
    "Noto Sans Coptic",
    "Avenir Next Condensed Demi Bold",
    "Noto Sans New Tai Lue",
    "Segoe UI Historic Regular",
    "MT Extra",
    "Microsoft YaHei",
    "Hiragino Kaku Gothic Std W8",
    "STIXIntegralsD-Bold",
    "HELV",
    "URW Bookman",
    "Corsiva Hebrew",
    "MS Serif Regular",
    "Magneto",
    "Kohinoor Bangla",
    "Noto Sans Syriac",
    "Terminal",
    "Devanagari Sangam MN",
    "Gayathri",
    "Courier New",
    "Levenim MT",
    "C059",
    "Wingdings Regular",
    "Serifa",
    "Consolas",
    "Waseem",
    "STIXSizeFourSym-Regular",
    "Perpetua",
    "Segoe MDL2 Assets Regular",
    "NTR",
    "Avenir Black",
    "Farah",
    "Loma",
    "MS Mincho",
    "Laksaman",
    "Comic Sans MS Bold",
    "Aqua Kana",
    "Sitka Text",
    "PingFang TC",
    "STIXVariants-Regular",
    "Yu Gothic",
    "Luminari",
    "Noto Sans Lycian",
    "Noto Sans Cham",
    "Gurajada",
    "Hiragino Kaku Gothic Pro W3",
    "Uroob",
    "Nakula",
    "Shree Devanagari 714 Italic",
    "Noto Sans Pahawh Hmong",
    "Avenir Next Heavy",
    "P052",
    "Courier 10 Pitch",
    "Gurmukhi MN",
    "Avenir Medium",
    "Telugu MN",
    "Malgun Gothic",
    "cursive",
    "Arial",
    "Old English Text MT",
    "KacstPen",
    "STIXSizeOneSym-Regular",
    "Noto Sans Myanmar",
    "Vrinda",
    "Hoefler Text",
    "GB18030 Bitmap",
    "Seravek Medium",
    "Wingdings 3",
    "Lohit Tamil Classical",
    "Noto Sans Osmanya",
    "Noto Sans Linear A",
    "System Bold",
    "Stencil",
    "Segoe MDL2 Assets",
    "Marlett",
    "Optima",
    "Futura Md BT",
    "Nirmala UI Semilight",
    "Noto Sans Tifinagh",
    "padmmaa",
    "Noto Serif Myanmar",
    "Noto Sans Mono",
    "SimHei",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Old South Arabian",
    "Playbill",
    "Noto Mono",
    "Lucida Sans Unicode Regular",
    "Charter",
    "utkal",
    "FreeMono",
    "Yu Gothic Light",
    "Seravek",
    "Futura Bk BT",
    "Trebuchet MS",
    "Hiragino Maru Gothic ProN W4",
    "Hiragino Sans",
    "MS PGothic Regular",
    "Noto Sans Linear B",
    "Skia",
    "Rockwell Extra Bold",
    "padmaa-Bold.1.1",
    "Niagara Engraved",
    "Viner Hand ITC",
    "Lohit Tamil",
    "MingLiU-ExtB",
    "Proxy 9",
    "TRAJAN PRO",
    "Proxy 3",
    "Noto Sans Buginese",
    "Dhurjati",
    "MS Sans Serif Regular",
    "Avenir",
    "EUROSTILE",
    "Segoe UI Historic",
    "Cambria",
    "Herculanum",
    "STIXIntegralsUp-Bold",
    "Javanese Text Regular",
    "Proxy 2",
    "Al Tarikh",
    "Liberation Mono",
    "Iowan Old Style Black",
    "Small Fonts",
    "Modern No. 20",
    "AR PL UKai TW MBE",
    "Hiragino Mincho Pro W6",
    "Comic Sans",
    "Modern",
    "DengXian",
    "Rasa Light",
    "Muna",
    "Khmer OS System",
    "DejaVu Serif",
    "Noto Sans CJK JP",
    "STIXNonUnicode-BoldItalic",
    "Mongolia Baiti Regular",
    "Noto Sans Sundanese",
    "Bodoni MT Black",
    "Arial Narrow",
    "Wingdings 2",
    "DejaVu Sans",
    "KacstLetter",
    "Apple Chancery",
    "Gill Sans",
    "Norasi",
    "MV Boli",
    "MingLiU",
    "Garamond",
    "Noto Sans Elbasan",
    "Helvetica Neue",
    "STFangsong",
    "PT Sans",
    "Oriya MN",
    "LastResort",
    "Gabriola Regular",
    "Blackadder ITC",
    "Gurmukhi MT",
    "Noto Sans Khudawadi",
    "Suranna",
    "Kohinoor Gujarati",
    "STIXVariants-Bold",
    "Hiragino Kaku Gothic ProN W3",
    "Hiragino Sans W6",
    "Hiragino Kaku Gothic Std",
    "Diwan Thuluth",
    "Webdings",
    "Microsoft JhengHei",
    "AR PL UKai CN",
    "Chalkboard SE",
    "MYRIAD PRO",
    "Noto Sans Old Turkic",
    "Noto Sans Tai Tham",
    "Yu Gothic UI Light",
    "AR PL UKai HK",
    "Noto Sans Mongolian",
    "Tw Cen MT",
    "Script Regular",
    "Juice ITC",
    "Sylfaen Regular",
    "Eurostile",
    "Raanana",
    "Hiragino Sans GB",
    "mry_KacstQurn",
    "Copperplate",
    "Mishafi Gold",
    "Umpush",
    "Constantia",
    "Microsoft Tai Le",
    "Z003",
    "Script",
    "Times New Roman",
    "Noto Sans Carian",
    "Ramabhadra",
    "Gayathri Thin",
    "Sitka Heading",
    "Sinhala MN",
    "Microsoft PhangsPa",
    "Tempus Sans ITC",
    "Superclarendon",
    "Kalimati",
    "Myanmar Text",
    "Vivaldi",
    "MS PMincho",
    "Malayalam Sangam MN",
    "KacstDecorative",
    "Noto Sans Mende Kikakui",
    "Myanmar Sangam MN",
    "Noto Sans Rejang",
    "Roman Regular",
    "Ravie",
    "Humanst521 BT",
    "Lucida Calligraphy",
    "STIXSizeThreeSym-Bold",
    "Hiragino Mincho ProN W3",
    "Gidugu",
    "STIXIntegralsUpSm-Bold",
    "Droid Sans Fallback",
    "Segoe UI Symbol",
    "Noto Sans Armenian",
    "Noto Sans Ugaritic",
    "KacstBook",
    "Sitka Subheading",
    "Kristen ITC",
    "Goudy Stout",
    "Manjari",
    "Monaco",
    "Aqua Kana Bold",
    "Devanagari MT",
    "Microsoft Sans Serif",
    "Yu Gothic UI Semilight",
    "Noto Sans CJK KR",
    "AR PL UMing CN",
    "Segoe UI Light",
    "Mongolian Baiti",
    "AR PL UMing TW",
    "Palace Script MT",
    "STIXIntegralsD-Regular",
    "Rockwell Condensed",
    "Menlo",
    "Microsoft New Tai Lue",
    "Proxy 6",
    "STIXVariants",
    "Microsoft JhengHei UI",
    "Avenir Next Condensed Medium",
    "Noto Sans Mono CJK SC",
    "PMingLiU",
    "Tw Cen MT Condensed",
    "Hiragino Sans GB W6",
    "Athelas",
    "Bodoni 72 Smallcaps",
    "Lucida Console",
    "Hiragino Sans W7",
    "STIXGeneral-Bold",
    "Tlwg Mono",
    "Colonna MT",
    "Franklin Gothic Medium",
    "Cambria Math",
    "Segoe Script",
    "Brush Script MT",
    "AppleGothic",
    "SignPainter-HouseScript",
    "Microsoft JhengHei Regular",
    "sans-serif",
    "Sathu",
    "SCRIPTINA",
    "Apple Braille",
    "Lucida Sans Unicode",
    "MingLiU_HKSCS",
    "STKaiti",
    "Microsoft JhengHei UI Regular",
    "Wide Latin",
    "Segoe Print",
    "Californian FB",
    "Noto Sans Palmyrene",
    "Wingdings",
    "Timmana",
    "Arial Rounded MT Bold",
    "Noto Sans Kayah Li",
    "Yu Gothic UI Regular",
    "Suravaram",
    "Padauk",
    "Abyssinica SIL",
    "Impact",
    "Noto Sans Kaithi",
    "Khmer OS",
    "Manjari Thin",
    "STIXIntegralsUpSm-Regular",
    "Didot",
    "Pristina",
    "Hiragino Sans W3",
    "Noto Sans Thaana",
    "STIXSizeTwoSym",
    "STIXNonUnicode-Bold",
    "Noto Serif CJK JP",
    "Khmer Sangam MN",
    "Times",
    "Chiller",
    "arial",
    "Perpetua Titling MT",
    "Rasa SemiBold",
    "Centaur",
    "Adobe Devanagari",
    "Yu Gothic UI Semibold",
    "Ink Free",
    "Standard Symbols PS",
    "Noto Sans Tai Viet",
    "Nadeem",
    "PingFang HK",
    "STIXSizeOneSym-Bold",
    "Ayuthaya",
    "PT Serif",
    "Zapfino",
    "French Script MT",
    "FreeSans",
    "Calisto MT",
    "Noto Sans Takri",
    "LKLUG",
    "STIXSizeOneSym",
    "Batang",
    "Tahoma",
    "Noto Sans Pau Cin Hau",
    "aakar",
    "Britannic Bold",
    "Avenir Next Condensed Ultra Light",
    "Chilanka",
    "Javanese Text",
    "Meera",
    "Noto Sans Marchen",
    "MS Sans Serif",
    "Lucida Fax",
    "Navilu",
    "Sree Krushnadevaraya",
    "New Peninim MT",
    "Freestyle Script",
    "Ubuntu Condensed",
    "Bradley Hand",
    "STFangSong",
    "Algerian",
    "Noto Serif Balinese",
    "STIXNonUnicode-Italic",
    "Kokonor",
    "Arial Unicode MS",
    "Sitka Display",
    "Meiryo",
    "Noto Serif CJK SC",
    "Onyx",
    "Sitka Small",
    "Proxy 8",
    "Gadugi",
    "Tlwg Typist",
    "Noto Sans Meetei Mayek",
    "Noto Sans Khojki",
    "High Tower Text",
    "Lucida Sans Typewriter",
    "Lohit Odia",
    "no-real-font-590",
    "AR PL UMing HK",
    "Noto Sans Inscriptional Parthian",
    "monospace",
    "Bernard MT Condensed",
    "Baskerville Old Face",
    "Bahnschrift SemiBold",
    "Bodoni MT",
    "Bodoni MT Condensed",
    "Bradley Hand ITC",
    "Broadway",
    "Candara",
    "Century Schoolbook",
    "Copperplate Gothic Light",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Franklin Gothic Heavy",
    "Gigi",
    "Harrington",
    "Jokerman",
    "Kunstler Script",
    "Lucida Handwriting",
    "Lucida Sans",
    "MS Gothic",
    "MS Outlook",
    "Microsoft JhengHei Light",
    "Microsoft PhagsPa",
    "Microsoft YaHei UI Light",
    "Nirmala UI",
    "PMingLiU-ExtB",
    "Proxy 1",
    "STXihei",
    "Segoe UI Semibold",
    "no-real-font-123",
    "sans-serif-thin",
    "Bitstream Vera Sans Mono",
    "Avenir Black Oblique",
    "Bodoni 72",
    "Gulim",
    "Heiti TC",
    "Hiragino Sans GB W3",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "Marion",
    "Noto Sans Adlam",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Buhid",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans NKo",
    "Noto Sans Old North Arabian",
    "Noto Sans Oriya",
    "Noto Sans PhagsPa",
    "Noto Sans Runic",
    "Noto Sans Samaritan",
    "Noto Sans Sharada",
    "Noto Sans Syloti Nagri",
    "Noto Sans Tirhuta",
    "Noto Sans Yi",
    "STIXIntegralsSm-Bold",
    "STIXNonUnicode",
    "STIXSizeFourSym-Bold",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Caurier Regular",
    "HoloLens MDL2 Assets Regular",
    "Microsoft Yi Baiti Regular",
    "MV Boli Regular",
    "Myanmar Tet",
    "Segoe UI Symbol Regular",
    "SimSun Regular",
    "SimSun-ExtB Regular",
    "Webdings Regular",
    "Leelawadee UI Semilight",
    "Segoe UI Semilight",
    "Liberation Sans",
    "Garuda",
    "Gubbi",
    "KacstFarsi",
    "KacstOffice",
    "KacstTitle",
    "Lohit Assamese",
    "Nimbus Sans Narrow",
    "Noto Sans CJK TC",
    "Noto Sans Mono CJK JP",
    "Noto Serif CJK KR",
    "OpenSymbol",
    "Pothana2000",
    "Rachana",
    "Yrsa SemiBold",
    "Saab",
    "Samyak Malayalam",
    "Sarai",
    "Tlwg Typo",
    "Ubuntu Mono",
];

// ========== 字体平台分类 ==========
// 以下常量将字体按平台和用途分类，便于跨平台应用选择合适的字体回退方案

/// macOS 独有字体（Apple 系统字体及 Mac 预装字体）
pub const FONTS_MAC_ONLY: &[&str] = &[
    "Al Bayan",
    "Al Tarikh",
    "American Typewriter",
    "Andale Mono",
    "Apple Braille",
    "Apple Braille Pinpoint 6 Dot",
    "Apple Braille Pinpoint 8 Dot",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "Avenir",
    "Avenir Black",
    "Avenir Black Oblique",
    "Avenir Book",
    "Avenir Heavy",
    "Avenir Light",
    "Avenir Medium",
    "Avenir Next",
    "Avenir Next Condensed",
    "Avenir Next Condensed Demi Bold",
    "Avenir Next Condensed Heavy",
    "Avenir Next Condensed Medium",
    "Avenir Next Condensed Ultra Light",
    "Avenir Next Demi Bold",
    "Avenir Next Heavy",
    "Avenir Next Medium",
    "Avenir Next Ultra Light",
    "Aqua Kana",
    "Aqua Kana Bold",
    "AquaKana",
    "Athelas",
    "Baskerville",
    "Big Caslon",
    "BlinkMacSystemFont",
    "Chalkboard",
    "Chalkboard SE",
    "Chalkduster",
    "Charter",
    "Charter Black",
    "Cochin",
    "Copperplate",
    "Didot",
    "Geeza Pro",
    "Geneva",
    "Heiti SC",
    "Heiti TC",
    "Helvetica",
    "Helvetica Neue",
    "Herculanum",
    "Hiragino Kaku Gothic Pro",
    "Hiragino Kaku Gothic ProN",
    "Hiragino Kaku Gothic ProN W3",
    "Hiragino Kaku Gothic ProN W6",
    "Hiragino Kaku Gothic Pro W3",
    "Hiragino Kaku Gothic Pro W6",
    "Hiragino Kaku Gothic Std",
    "Hiragino Kaku Gothic StdN",
    "Hiragino Kaku Gothic StdN W8",
    "Hiragino Kaku Gothic Std W8",
    "Hiragino Maru Gothic Pro",
    "Hiragino Maru Gothic ProN",
    "Hiragino Maru Gothic ProN W4",
    "Hiragino Maru Gothic Pro W4",
    "Hiragino Mincho Pro",
    "Hiragino Mincho ProN",
    "Hiragino Mincho ProN W3",
    "Hiragino Mincho ProN W6",
    "Hiragino Mincho Pro W3",
    "Hiragino Mincho Pro W6",
    "Hiragino Sans",
    "Hiragino Sans GB",
    "Hiragino Sans GB W3",
    "Hiragino Sans GB W6",
    "Hiragino Sans W0",
    "Hiragino Sans W1",
    "Hiragino Sans W2",
    "Hiragino Sans W3",
    "Hiragino Sans W4",
    "Hiragino Sans W5",
    "Hiragino Sans W6",
    "Hiragino Sans W7",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "Hiragino Kaku Gothic StdN W8",
    "Hoefler Text",
    "Hoefler Text Ornaments",
    "Iowan Old Style",
    "Iowan Old Style Black",
    "Keyboard",
    "LastResort",
    "Lucida Grande",
    "Luminari",
    "Marker Felt",
    "Menlo",
    "Monaco",
    "Noteworthy",
    "Optima",
    "Phosphate",
    "PingFang HK",
    "PingFang SC",
    "PingFang TC",
    "Sathu",
    "Seravek",
    "Seravek ExtraLight",
    "Seravek Light",
    "Seravek Medium",
    "SignPainter",
    "SignPainter-HouseScript",
    "Skia",
    "Snell Roundhand",
    "Songti SC",
    "Songti TC",
    "STFangSong",
    "STKaiti",
    "STSong",
    "STXihei",
    "Trattatello",
    "Zapfino",
    "Bangla MN",
    "Bangla Sangam MN",
    "Devanagari Sangam MN",
    "Gujarati Sangam MN",
    "Gurmukhi MN",
    "Gurmukhi Sangam MN",
    "Kannada MN",
    "Kannada Sangam MN",
    "Khmer MN",
    "Khmer Sangam MN",
    "Lao MN",
    "Lao Sangam MN",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Oriya MN",
    "Oriya Sangam MN",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Tamil MN",
    "Tamil Sangam MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "GB18030 Bitmap",
    "Bodoni Ornaments",
    "Bodoni 72",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "DecoType Naskh",
    "Euphemia UCAS",
    "Galvji",
];

/// Windows 独有字体（Microsoft 系统字体及 Windows 预装字体）
pub const FONTS_WINDOWS_ONLY: &[&str] = &[
    "Bahnschrift",
    "Bahnschrift Light",
    "Bahnschrift SemiBold",
    "Calibri",
    "Calibri Light",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Comic Sans MS",
    "Comic Sans MS Bold",
    "Comic Sans",
    "Consolas",
    "Constantia",
    "Corbel",
    "Corbel Light",
    "DengXian",
    "DengXian Light",
    "Fixedsys",
    "Fixedsys Regular",
    "Gabriola",
    "Gabriola Regular",
    "Gadugi",
    "HoloLens MDL2 Assets",
    "HoloLens MDL2 Assets Regular",
    "Ink Free",
    "Leelawadee",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Console",
    "Lucida Console Regular",
    "Lucida Sans Unicode",
    "Lucida Sans Unicode Regular",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Meiryo",
    "Meiryo UI",
    "Microsoft Himalaya",
    "Microsoft Himalaya Regular",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei Regular",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft JhengHei UI Regular",
    "Microsoft New Tai Lue",
    "Microsoft PhangsPa",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Sans Serif Regular",
    "Microsoft Tai Le",
    "Microsoft Uighur",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",
    "Microsoft Yi Baiti Regular",
    "MingLiU",
    "MingLiU-ExtB",
    "MingLiU-ExtB Regular",
    "MingLiU_HKSCS",
    "MingLiU_HKSCS-ExtB",
    "MingLiU_HKSCS-ExtB Regular",
    "Mongolian Baiti",
    "Mongolia Baiti Regular",
    "MS Gothic",
    "MS Gothic Regular",
    "MS Mincho",
    "MS Outlook",
    "MS PGothic",
    "MS PGothic Regular",
    "MS PMincho",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Sans Serif Regular",
    "MS Serif",
    "MS Serif Regular",
    "MS UI Gothic",
    "MS UI Gothic Regular",
    "MV Boli",
    "MV Boli Regular",
    "Myanmar Text",
    "Myanmar Tet",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "NSimSun",
    "NSimSun Regular",
    "Palatino Linotype",
    "PMingLiU",
    "PMingLiU-ExtB",
    "PMingLiU-ExtB Regular",
    "Segoe MDL2 Assets",
    "Segoe MDL2 Assets Regular",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Emoji Regular",
    "Segoe UI Historic",
    "Segoe UI Historic Regular",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Segoe UI Symbol Regular",
    "SimHei",
    "SimSun",
    "SimSun Regular",
    "SimSun-ExtB",
    "SimSun-ExtB Regular",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka Text",
    "Tahoma",
    "Terminal",
    "Webdings",
    "Webdings Regular",
    "Wingdings",
    "Wingdings Regular",
    "Wingdings 2",
    "Wingdings 3",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic Regular",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Regular",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
];

/// Linux 独有/常用字体（开源字体，多预装于 Linux 发行版）
pub const FONTS_LINUX_ONLY: &[&str] = &[
    "Bitstream Vera Sans Mono",
    "Courier 10 Pitch",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Droid Sans Fallback",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Garuda",
    "Gubbi",
    "KacstArt",
    "KacstBook",
    "KacstDecorative",
    "KacstDigital",
    "KacstFarsi",
    "KacstLetter",
    "KacstNaskh",
    "KacstOffice",
    "KacstOne",
    "KacstPen",
    "KacstPoster",
    "KacstQurn",
    "KacstScreen",
    "KacstTitle",
    "KacstTitleL",
    "LKLUG",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Sans Narrow",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "OpenSymbol",
    "Tlwg Mono",
    "Tlwg Typewriter",
    "Tlwg Typist",
    "Tlwg Typo",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Light",
    "Ubuntu Mono",
    "Ubuntu Thin",
    "URW Bookman",
    "URW Gothic",
];

/// 全平台通用字体（Mac、Windows、Linux 均常见）
pub const FONTS_CROSS_PLATFORM: &[&str] = &[
    "Arial",
    "Arial Black",
    "Arial Hebrew",
    "Arial Hebrew Scholar",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "arial",
    "Courier New",
    "Courier",
    "Georgia",
    "Impact",
    "Impact Regular",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Roboto",
    "Google Sans",
    "Noto Sans",
    "Noto Serif",
    "Noto Mono",
    "Noto Sans Mono",
    "Noto Color Emoji",
    "Times New Roman",
    "Times",
    "Trebuchet MS",
    "Verdana",
    "Symbol",
    "Symbol Regular",
    "Zapf Dingbats",
];

/// 特定语言/书写系统独有字体（为特定语言或书写系统设计）
pub const FONTS_LANGUAGE_SPECIFIC: &[&str] = &[
    // 阿拉伯语
    "Al Nile",
    "Baghdad",
    "Corsiva Hebrew",
    "Damascus",
    "Diwan Kufi",
    "Diwan Thuluth",
    "Farah",
    "Farisi",
    "KufiStandardGK",
    "Mishafi",
    "Mishafi Gold",
    "Muna",
    "Nadeem",
    "New Peninim MT",
    "Raanana",
    "Waseem",
    "Arabic Typesetting",
    "Microsoft Uighur",
    // 希伯来语
    "Arial Hebrew",
    "Corsiva Hebrew",
    "Levenim MT",
    "New Peninim MT",
    "Raanana",
    // 印度诸语系
    "AnjaliOldLipi",
    "Devanagari MT",
    "Gujarati MT",
    "Gurmukhi MT",
    "InaiMathi",
    "ITF Devanagari",
    "ITF Devanagari Marathi",
    "Kohinoor Bangla",
    "Kohinoor Devanagari",
    "Kohinoor Gujarati",
    "Kohinoor Telugu",
    "Lohit Assamese",
    "Lohit Bengali",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Gurmukhi",
    "Lohit Kannada",
    "Lohit Malayalam",
    "Lohit Odia",
    "Lohit Tamil",
    "Lohit Tamil Classical",
    "Lohit Telugu",
    "Noto Sans Brahmi",
    "Noto Sans Devanagari",
    "Noto Sans Gujarati",
    "Noto Sans Gurmukhi",
    "Noto Sans Kannada",
    "Noto Sans Malayalam",
    "Noto Sans Tamil",
    "Noto Sans Telugu",
    "Noto Serif Ahom",
    "Rachana",
    "Samyak Devanagari",
    "Samyak Gujarati",
    "Samyak Malayalam",
    "Samyak Tamil",
    "Shree Devanagari 714",
    "Shree Devanagari 714 Bold",
    "Shree Devanagari 714 Bold Italic",
    "Shree Devanagari 714 Italic",
    // 东南亚语言
    "Ayuthaya",
    "Beirut",
    "Khmer OS",
    "Khmer OS System",
    "Krungthep",
    "Lao Sangam MN",
    "Phetsarath OT",
    "Phetsarath OT",
    "Sawasdee",
    "Silom",
    "Sukhumvit Set",
    "Thonburi",
    "Padauk",
    "Padauk Book",
    "Myanmar Text",
    "Noto Sans Myanmar",
    "Noto Serif Myanmar",
    // 藏语/蒙古语
    "Kokonor",
    "Tibetan Machine Uni",
    "Mongolian Baiti",
    "Noto Sans Mongolian",
    // CJK - Noto 系列（跨平台）
    "Noto Sans CJK JP",
    "Noto Sans CJK KR",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans CJK HK",
    "Noto Sans Mono CJK JP",
    "Noto Sans Mono CJK KR",
    "Noto Sans Mono CJK SC",
    "Noto Sans Mono CJK TC",
    "Noto Sans Mono CJK HK",
    "Noto Serif CJK JP",
    "Noto Serif CJK KR",
    "Noto Serif CJK SC",
    "Noto Serif CJK TC",
    // 其他历史/少数民族文字
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kharoshthi",
    "Noto Sans Khudawadi",
    "Noto Sans Kayah Li",
    "Noto Sans Lydian",
    "Noto Sans Lycian",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Limbu",
    "Noto Sans Lisu",
    "Noto Sans Lepcha",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Meetei Mayek",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Multani",
    "Noto Sans Nabataean",
    "Noto Sans NKo",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans Ogham",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old Italic",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Runic",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Shavian",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Serif Balinese",
    "Noto Nastaliq Urdu",
    // 古吉拉特、泰米尔等南亚字体
    "Chandas",
    "Dhurjati",
    "Dyuthi",
    "Gargi",
    "Gayathri",
    "Gayathri Thin",
    "Gidugu",
    "Gurajada",
    "Jamrul",
    "Kalapi",
    "Kalimati",
    "Karumbi",
    "Keraleeyam",
    "Kinnari",
    "Lakshman",
    "Laksaman",
    "Mallanna",
    "Manjari",
    "Manjari Thin",
    "Meera",
    "Navilu",
    "Norasi",
    "Peddana",
    "RaghuMalayalamSans",
    "RaghuMalayalamSans",
    "Ramaraja",
    "Ramabhadra",
    "Rasa",
    "Rasa Light",
    "Rasa Medium",
    "Rasa SemiBold",
    "Rekha",
    "Sahadeva",
    "Samanata",
    "Sarai",
    "Suravaram",
    "Suruma",
    "Suranna",
    "Timmana",
    "Uroob",
    "Vemana2000",
    "Waree",
];
