// Generated from uploaded fonts.rs after:
// - reusing entries that can plausibly appear on Linux
// - supplementing Linux generic family aliases
// - supplementing official/common distro desktop fonts (GNOME, Ubuntu, Debian/Fedora packages)
// - keeping the list family-name oriented for Chromium/fontconfig style matching
//
// Source baseline: /mnt/data/fonts.rs
// Original ALL_FONTS entries: 991
// Original unique exact names: 854
// Reused from uploaded list: 271
// Added Linux supplements/aliases: 27
// Final Linux-oriented names: 298

/// Generic family aliases commonly resolved by Linux/fontconfig/CSS stacks.
pub const LINUX_GENERIC_ALIASES: &[&str] = &[
    "sans-serif",
    "serif",
    "monospace",
    "cursive",
    "fantasy",
    "emoji",
    "math",
    "system-ui",
    "ui-sans-serif",
    "ui-serif",
    "ui-monospace",
    "ui-rounded",
];

/// Supplemental Linux desktop/distro families added on top of the uploaded list.
pub const LINUX_OFFICIAL_SUPPLEMENTS: &[&str] = &[
    "Adwaita Mono",
    "Adwaita Sans",
    "Bitstream Vera Sans",
    "Bitstream Vera Serif",
    "C059",
    "Cantarell",
    "D050000L",
    "Liberation Serif",
    "Noto Emoji",
    "Noto Sans Math",
    "Noto Sans Symbols",
    "Noto Sans Symbols 2",
    "P052",
    "Standard Symbols PS",
    "Z003",
];

/// Entries reused from the uploaded list that can plausibly appear on Linux systems.
pub const LINUX_REUSED_FROM_UPLOADED: &[&str] = &[
    "Abyssinica SIL",
    "AnjaliOldLipi",
    "Arial",
    "arial",
    "Arial Black",
    "Arial Hebrew",
    "Arial Hebrew Scholar",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Bitstream Vera Sans Mono",
    "Charter",
    "Courier",
    "Courier 10 Pitch",
    "Courier New",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Droid Sans Fallback",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Garuda",
    "Georgia",
    "Google Sans",
    "Gubbi",
    "Impact",
    "Impact Regular",
    "KacstArt",
    "KacstBook",
    "KacstDecorative",
    "KacstDigital",
    "KacstFarsi",
    "KacstLetter",
    "KacstNaskh",
    "KacstOffice",
    "KacstOne",
    "KacstPen",
    "KacstPoster",
    "KacstQurn",
    "KacstScreen",
    "KacstTitle",
    "KacstTitleL",
    "Khmer OS",
    "Khmer OS System",
    "Kinnari",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Sans Narrow",
    "LKLUG",
    "Lohit Assamese",
    "Lohit Bengali",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Gurmukhi",
    "Lohit Kannada",
    "Lohit Malayalam",
    "Lohit Odia",
    "Lohit Tamil",
    "Lohit Tamil Classical",
    "Lohit Telugu",
    "Loma",
    "mry_KacstQurn",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "Norasi",
    "Noto Color Emoji",
    "Noto Mono",
    "Noto Nastaliq Urdu",
    "Noto Sans",
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Bassa Vah",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans CJK HK",
    "Noto Sans CJK JP",
    "Noto Sans CJK KR",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kannada",
    "Noto Sans Kayah Li",
    "Noto Sans Kharoshthi",
    "Noto Sans Khojki",
    "Noto Sans Khudawadi",
    "Noto Sans Lepcha",
    "Noto Sans Limbu",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Lisu",
    "Noto Sans Lycian",
    "Noto Sans Lydian",
    "Noto Sans Mahajani",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Meetei Mayek",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Mongolian",
    "Noto Sans Mono",
    "Noto Sans Mono CJK HK",
    "Noto Sans Mono CJK JP",
    "Noto Sans Mono CJK KR",
    "Noto Sans Mono CJK SC",
    "Noto Sans Mono CJK TC",
    "Noto Sans Mro",
    "Noto Sans Multani",
    "Noto Sans Myanmar",
    "Noto Sans Nabataean",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans NKo",
    "Noto Sans Ogham",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old Italic",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Oriya",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Runic",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Shavian",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Serif",
    "Noto Serif Ahom",
    "Noto Serif Balinese",
    "Noto Serif CJK JP",
    "Noto Serif CJK KR",
    "Noto Serif CJK SC",
    "Noto Serif CJK TC",
    "Noto Serif Myanmar",
    "OpenSymbol",
    "Padauk",
    "Padauk Book",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Purisa",
    "Rachana",
    "Roboto",
    "Samyak Devanagari",
    "Samyak Gujarati",
    "Samyak Malayalam",
    "Samyak Tamil",
    "Sana",
    "Sathu",
    "Sawasdee",
    "STIXGeneral",
    "STIXGeneral-Bold",
    "STIXGeneral-BoldItalic",
    "STIXGeneral-Italic",
    "STIXGeneral-Regular",
    "STIXIntegralsD",
    "STIXIntegralsD-Bold",
    "STIXIntegralsD-Regular",
    "STIXIntegralsSm",
    "STIXIntegralsSm-Bold",
    "STIXIntegralsSm-Regular",
    "STIXIntegralsUp",
    "STIXIntegralsUp-Bold",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsUpD",
    "STIXIntegralsUpD-Bold",
    "STIXIntegralsUpD-Regular",
    "STIXIntegralsUpSm",
    "STIXIntegralsUpSm-Bold",
    "STIXIntegralsUpSm-Regular",
    "STIXNonUnicode",
    "STIXNonUnicode-Bold",
    "STIXNonUnicode-BoldItalic",
    "STIXNonUnicode-Italic",
    "STIXNonUnicode-Regular",
    "STIXSizeFiveSym",
    "STIXSizeFiveSym-Regular",
    "STIXSizeFourSym",
    "STIXSizeFourSym-Bold",
    "STIXSizeFourSym-Regular",
    "STIXSizeOneSym",
    "STIXSizeOneSym-Bold",
    "STIXSizeOneSym-Regular",
    "STIXSizeThreeSym",
    "STIXSizeThreeSym-Bold",
    "STIXSizeThreeSym-Regular",
    "STIXSizeTwoSym",
    "STIXSizeTwoSym-Bold",
    "STIXSizeTwoSym-Regular",
    "STIXVariants",
    "STIXVariants-Bold",
    "STIXVariants-Regular",
    "Symbol",
    "Symbol Regular",
    "Times",
    "Times New Roman",
    "Tlwg Mono",
    "Tlwg Typewriter",
    "Tlwg Typist",
    "Tlwg Typo",
    "Trebuchet MS",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Light",
    "Ubuntu Mono",
    "Ubuntu Thin",
    "Umpush",
    "URW Bookman",
    "URW Gothic",
    "Verdana",
    "Waree",
    "Zapf Dingbats",
];

/// Final Linux-oriented font family list.
pub const LINUX_SYSTEM_FONTS: &[&str] = &[
    "Abyssinica SIL",
    "Adwaita Mono",
    "Adwaita Sans",
    "AnjaliOldLipi",
    "Arial",
    "arial",
    "Arial Black",
    "Arial Hebrew",
    "Arial Hebrew Scholar",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Bitstream Vera Sans",
    "Bitstream Vera Sans Mono",
    "Bitstream Vera Serif",
    "C059",
    "Cantarell",
    "Charter",
    "Courier",
    "Courier 10 Pitch",
    "Courier New",
    "cursive",
    "D050000L",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Droid Sans Fallback",
    "emoji",
    "fantasy",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Garuda",
    "Georgia",
    "Google Sans",
    "Gubbi",
    "Impact",
    "Impact Regular",
    "KacstArt",
    "KacstBook",
    "KacstDecorative",
    "KacstDigital",
    "KacstFarsi",
    "KacstLetter",
    "KacstNaskh",
    "KacstOffice",
    "KacstOne",
    "KacstPen",
    "KacstPoster",
    "KacstQurn",
    "KacstScreen",
    "KacstTitle",
    "KacstTitleL",
    "Khmer OS",
    "Khmer OS System",
    "Kinnari",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Sans Narrow",
    "Liberation Serif",
    "LKLUG",
    "Lohit Assamese",
    "Lohit Bengali",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Gurmukhi",
    "Lohit Kannada",
    "Lohit Malayalam",
    "Lohit Odia",
    "Lohit Tamil",
    "Lohit Tamil Classical",
    "Lohit Telugu",
    "Loma",
    "math",
    "monospace",
    "mry_KacstQurn",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "Norasi",
    "Noto Color Emoji",
    "Noto Emoji",
    "Noto Mono",
    "Noto Nastaliq Urdu",
    "Noto Sans",
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Bassa Vah",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans CJK HK",
    "Noto Sans CJK JP",
    "Noto Sans CJK KR",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kannada",
    "Noto Sans Kayah Li",
    "Noto Sans Kharoshthi",
    "Noto Sans Khojki",
    "Noto Sans Khudawadi",
    "Noto Sans Lepcha",
    "Noto Sans Limbu",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Lisu",
    "Noto Sans Lycian",
    "Noto Sans Lydian",
    "Noto Sans Mahajani",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Math",
    "Noto Sans Meetei Mayek",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Mongolian",
    "Noto Sans Mono",
    "Noto Sans Mono CJK HK",
    "Noto Sans Mono CJK JP",
    "Noto Sans Mono CJK KR",
    "Noto Sans Mono CJK SC",
    "Noto Sans Mono CJK TC",
    "Noto Sans Mro",
    "Noto Sans Multani",
    "Noto Sans Myanmar",
    "Noto Sans Nabataean",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans NKo",
    "Noto Sans Ogham",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old Italic",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Oriya",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Runic",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Shavian",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Symbols",
    "Noto Sans Symbols 2",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Serif",
    "Noto Serif Ahom",
    "Noto Serif Balinese",
    "Noto Serif CJK JP",
    "Noto Serif CJK KR",
    "Noto Serif CJK SC",
    "Noto Serif CJK TC",
    "Noto Serif Myanmar",
    "OpenSymbol",
    "P052",
    "Padauk",
    "Padauk Book",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Purisa",
    "Rachana",
    "Roboto",
    "Samyak Devanagari",
    "Samyak Gujarati",
    "Samyak Malayalam",
    "Samyak Tamil",
    "Sana",
    "sans-serif",
    "Sathu",
    "Sawasdee",
    "serif",
    "Standard Symbols PS",
    "STIXGeneral",
    "STIXGeneral-Bold",
    "STIXGeneral-BoldItalic",
    "STIXGeneral-Italic",
    "STIXGeneral-Regular",
    "STIXIntegralsD",
    "STIXIntegralsD-Bold",
    "STIXIntegralsD-Regular",
    "STIXIntegralsSm",
    "STIXIntegralsSm-Bold",
    "STIXIntegralsSm-Regular",
    "STIXIntegralsUp",
    "STIXIntegralsUp-Bold",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsUpD",
    "STIXIntegralsUpD-Bold",
    "STIXIntegralsUpD-Regular",
    "STIXIntegralsUpSm",
    "STIXIntegralsUpSm-Bold",
    "STIXIntegralsUpSm-Regular",
    "STIXNonUnicode",
    "STIXNonUnicode-Bold",
    "STIXNonUnicode-BoldItalic",
    "STIXNonUnicode-Italic",
    "STIXNonUnicode-Regular",
    "STIXSizeFiveSym",
    "STIXSizeFiveSym-Regular",
    "STIXSizeFourSym",
    "STIXSizeFourSym-Bold",
    "STIXSizeFourSym-Regular",
    "STIXSizeOneSym",
    "STIXSizeOneSym-Bold",
    "STIXSizeOneSym-Regular",
    "STIXSizeThreeSym",
    "STIXSizeThreeSym-Bold",
    "STIXSizeThreeSym-Regular",
    "STIXSizeTwoSym",
    "STIXSizeTwoSym-Bold",
    "STIXSizeTwoSym-Regular",
    "STIXVariants",
    "STIXVariants-Bold",
    "STIXVariants-Regular",
    "Symbol",
    "Symbol Regular",
    "system-ui",
    "Times",
    "Times New Roman",
    "Tlwg Mono",
    "Tlwg Typewriter",
    "Tlwg Typist",
    "Tlwg Typo",
    "Trebuchet MS",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Light",
    "Ubuntu Mono",
    "Ubuntu Thin",
    "ui-monospace",
    "ui-rounded",
    "ui-sans-serif",
    "ui-serif",
    "Umpush",
    "URW Bookman",
    "URW Gothic",
    "Verdana",
    "Waree",
    "Z003",
    "Zapf Dingbats",
];
