// Generated from uploaded fonts.rs after:
// - deduping exact duplicates
// - removing Windows-only / Linux-only entries
// - removing obvious placeholders / noise
// - supplementing Android AOSP family names and key iOS system families
//
// Source baseline: /mnt/data/fonts.rs
// Original ALL_FONTS entries: 991
// Original unique exact names: 854
// Final mobile-focused names: 754

/// Current AOSP/Android family names and aliases useful for Chromium mapping.
pub const ANDROID_AOSP_FAMILY_NAMES: &[&str] = &[
    "sans-serif",
    "sans-serif-thin",
    "sans-serif-light",
    "sans-serif-medium",
    "sans-serif-black",
    "arial",
    "helvetica",
    "tahoma",
    "verdana",
    "sans-serif-condensed",
    "sans-serif-condensed-light",
    "sans-serif-condensed-medium",
    "serif",
    "serif-bold",
    "times",
    "times new roman",
    "palatino",
    "georgia",
    "baskerville",
    "goudy",
    "fantasy",
    "ITC Stone Serif",
    "monospace",
    "sans-serif-monospace",
    "monaco",
    "serif-monospace",
    "courier",
    "courier new",
    "casual",
    "cursive",
    "sans-serif-smallcaps",
    "source-sans-pro",
    "source-sans-pro-semi-bold",
    "roboto-flex",
];

/// Key iOS / Apple system families and CSS UI aliases that were missing from the uploaded list.
pub const IOS_APPLE_MISSING_SUPPLEMENTS: &[&str] = &[
    "SF Pro",
    "SF Pro Rounded",
    "SF Compact",
    "SF Compact Rounded",
    "SF Mono",
    "SF Arabic",
    "SF Arabic Rounded",
    "SF Armenian",
    "SF Georgian",
    "SF Hebrew",
    "New York",
    "ui-rounded",
    "ui-serif",
    "ui-monospace",
    "ui-sans-serif",
    "Annai MN",
    "Apple LiGothic Medium",
    "Apple LiSung Light",
];

/// Entries removed as placeholders / noise / non-font pseudo names.
pub const REMOVED_NON_MOBILE_OR_INVALID: &[&str] = &[
    "Proxy 1",
    "Proxy 2",
    "Proxy 3",
    "Proxy 4",
    "Proxy 5",
    "Proxy 6",
    "Proxy 7",
    "Proxy 8",
    "Proxy 9",
    "default",
    "no-real-font-123",
    "no-real-font-590",
];

/// Cleaned Android + iOS oriented font list.
pub const MOBILE_SYSTEM_FONTS: &[&str] = &[
    "-apple-system",
    "aakar",
    "Abyssinica SIL",
    "Academy Engraved LET",
    "Adobe Devanagari",
    "Agency FB",
    "Al Bayan",
    "Al Nile",
    "Al Tarikh",
    "Algerian",
    "American Typewriter",
    "Andale Mono",
    "Ani",
    "AnjaliOldLipi",
    "Annai MN",
    "Apple Braille",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Apple Braille Pinpoint 6 Dot",
    "Apple Braille Pinpoint 8 Dot",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple LiGothic Medium",
    "Apple LiSung Light",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "Aqua Kana",
    "Aqua Kana Bold",
    "AquaKana",
    "AR PL UKai CN",
    "AR PL UKai HK",
    "AR PL UKai TW",
    "AR PL UKai TW MBE",
    "AR PL UMing CN",
    "AR PL UMing HK",
    "AR PL UMing TW",
    "AR PL UMing TW MBE",
    "Arabic Typesetting",
    "Arial",
    "arial",
    "Arial Black",
    "Arial Hebrew",
    "Arial Hebrew Scholar",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "ARNO PRO",
    "Athelas",
    "AvantGarde Bk BT",
    "Avenir",
    "Avenir Black",
    "Avenir Black Oblique",
    "Avenir Book",
    "Avenir Heavy",
    "Avenir Light",
    "Avenir Medium",
    "Avenir Next",
    "Avenir Next Condensed",
    "Avenir Next Condensed Demi Bold",
    "Avenir Next Condensed Heavy",
    "Avenir Next Condensed Medium",
    "Avenir Next Condensed Ultra Light",
    "Avenir Next Demi Bold",
    "Avenir Next Heavy",
    "Avenir Next Medium",
    "Avenir Next Ultra Light",
    "Ayuthaya",
    "Baghdad",
    "Bangla MN",
    "Bangla Sangam MN",
    "BankGothic Md BT",
    "Baskerville",
    "baskerville",
    "Baskerville Old Face",
    "Batang",
    "Bauhaus 93",
    "Beirut",
    "Bell MT",
    "Berlin Sans FB",
    "Bernard MT Condensed",
    "Big Caslon",
    "Blackadder ITC",
    "BlinkMacSystemFont",
    "Bodoni 72",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni Ornaments",
    "Book Antiqua",
    "Bookman Old Style",
    "Bookshelf Symbol 7",
    "Bradley Hand",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "C059",
    "Californian FB",
    "Calisto MT",
    "Castellar",
    "casual",
    "Caurier Regular",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chalkboard",
    "Chalkboard SE",
    "Chalkduster",
    "Chandas",
    "Charter",
    "Charter Black",
    "Chilanka",
    "Chiller",
    "Clarendon",
    "Cochin",
    "Colonna MT",
    "Cooper Black",
    "Copperplate",
    "Copperplate Gothic",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Corsiva Hebrew",
    "Courier",
    "courier",
    "Courier New",
    "courier new",
    "Curlz MT",
    "cursive",
    "D050000L",
    "Damascus",
    "DecoType Naskh",
    "Devanagari MT",
    "Devanagari Sangam MN",
    "Dhurjati",
    "Didot",
    "DIN Alternate",
    "DIN Condensed",
    "Diwan Kufi",
    "Diwan Thuluth",
    "Dyuthi",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Euphemia UCAS",
    "EUROSTILE",
    "Eurostile",
    "FangSong",
    "fantasy",
    "Farah",
    "Farisi",
    "Felix Titling",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic",
    "Franklin Gothic Book",
    "Franklin Gothic Heavy",
    "Franklin Gothic Medium",
    "Freestyle Script",
    "French Script MT",
    "Futura",
    "Futura Bk BT",
    "Futura Md BT",
    "Galvji",
    "Garamond",
    "Gargi",
    "Gayathri",
    "Gayathri Thin",
    "GB18030 Bitmap",
    "Geeza Pro",
    "Geneva",
    "Georgia",
    "georgia",
    "Gidugu",
    "Gigi",
    "Gill Sans",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gill Sans Ultra Bold",
    "Gloucester MT Extra Condensed",
    "Google Sans",
    "GOTHAM",
    "goudy",
    "Goudy Old Style",
    "Goudy Stout",
    "Gujarati MT",
    "Gujarati Sangam MN",
    "Gulim",
    "Gurajada",
    "Gurmukhi MN",
    "Gurmukhi MT",
    "Gurmukhi Sangam MN",
    "Haettenschweiler",
    "Harrington",
    "Heiti SC",
    "Heiti TC",
    "HELV",
    "Helvetica",
    "helvetica",
    "Helvetica LT MM",
    "Helvetica Neue",
    "Herculanum",
    "High Tower Text",
    "Hiragino Kaku Gothic Pro",
    "Hiragino Kaku Gothic Pro W3",
    "Hiragino Kaku Gothic Pro W6",
    "Hiragino Kaku Gothic ProN",
    "Hiragino Kaku Gothic ProN W3",
    "Hiragino Kaku Gothic ProN W6",
    "Hiragino Kaku Gothic Std",
    "Hiragino Kaku Gothic Std W8",
    "Hiragino Kaku Gothic StdN",
    "Hiragino Kaku Gothic StdN W8",
    "Hiragino Maru Gothic Pro",
    "Hiragino Maru Gothic Pro W4",
    "Hiragino Maru Gothic ProN",
    "Hiragino Maru Gothic ProN W4",
    "Hiragino Mincho Pro",
    "Hiragino Mincho Pro W3",
    "Hiragino Mincho Pro W6",
    "Hiragino Mincho ProN",
    "Hiragino Mincho ProN W3",
    "Hiragino Mincho ProN W6",
    "Hiragino Sans",
    "Hiragino Sans GB",
    "Hiragino Sans GB W3",
    "Hiragino Sans GB W6",
    "Hiragino Sans W0",
    "Hiragino Sans W1",
    "Hiragino Sans W2",
    "Hiragino Sans W3",
    "Hiragino Sans W4",
    "Hiragino Sans W5",
    "Hiragino Sans W6",
    "Hiragino Sans W7",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "Hoefler Text",
    "Hoefler Text Ornaments",
    "Humanst521 BT",
    "Impact",
    "Impact Regular",
    "Imprint MT Shadow",
    "InaiMathi",
    "Informal Roman",
    "Iowan Old Style",
    "Iowan Old Style Black",
    "ITC Stone Serif",
    "ITF Devanagari",
    "ITF Devanagari Marathi",
    "Jamrul",
    "Javanese Text",
    "Javanese Text Regular",
    "Jokerman",
    "Juice ITC",
    "Kailasa",
    "KaiTi",
    "Kalapi",
    "Kalimati",
    "Kannada MN",
    "Kannada Sangam MN",
    "Karumbi",
    "Kefa",
    "Keraleeyam",
    "Keyboard",
    "Khmer MN",
    "Khmer OS",
    "Khmer OS System",
    "Khmer Sangam MN",
    "Kinnari",
    "Kohinoor Bangla",
    "Kohinoor Devanagari",
    "Kohinoor Gujarati",
    "Kohinoor Telugu",
    "Kokonor",
    "Kristen ITC",
    "Krungthep",
    "KufiStandardGK",
    "Kunstler Script",
    "Laksaman",
    "Lao MN",
    "Lao Sangam MN",
    "LastResort",
    "Letter Gothic",
    "Levenim MT",
    "Likhan",
    "Lohit Assamese",
    "Lohit Bengali",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Gurmukhi",
    "Lohit Kannada",
    "Lohit Malayalam",
    "Lohit Odia",
    "Lohit Tamil",
    "Lohit Tamil Classical",
    "Lohit Telugu",
    "Loma",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Fax",
    "Lucida Grande",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Luminari",
    "Magneto",
    "Maiandra GD",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Mallanna",
    "Mandali",
    "Manjari",
    "Manjari Thin",
    "Marion",
    "Marker Felt",
    "Matura MT Script Capitals",
    "Meera",
    "Menlo",
    "MingLiu-ExtB Regular",
    "Minion Pro",
    "Mishafi",
    "Mishafi Gold",
    "Mistral",
    "Modern",
    "Modern No. 20",
    "Modern Regular",
    "Monaco",
    "monaco",
    "monospace",
    "Monotype Corsiva",
    "mry_KacstQurn",
    "Mshtakan",
    "MT Extra",
    "Muna",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "MYRIAD PRO",
    "Nadeem",
    "Nakula",
    "Navilu",
    "New Peninim MT",
    "New York",
    "News Gothic MT",
    "Niagara Engraved",
    "Niagara Solid",
    "Nimarla UI",
    "Norasi",
    "Noteworthy",
    "Noto Color Emoji",
    "Noto Mono",
    "Noto Nastaliq Urdu",
    "Noto Sans",
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Bassa Vah",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans CJK HK",
    "Noto Sans CJK JP",
    "Noto Sans CJK KR",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kannada",
    "Noto Sans Kayah Li",
    "Noto Sans Kharoshthi",
    "Noto Sans Khojki",
    "Noto Sans Khudawadi",
    "Noto Sans Lepcha",
    "Noto Sans Limbu",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Lisu",
    "Noto Sans Lycian",
    "Noto Sans Lydian",
    "Noto Sans Mahajani",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Meetei Mayek",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Mongolian",
    "Noto Sans Mono",
    "Noto Sans Mono CJK HK",
    "Noto Sans Mono CJK JP",
    "Noto Sans Mono CJK KR",
    "Noto Sans Mono CJK SC",
    "Noto Sans Mono CJK TC",
    "Noto Sans Mro",
    "Noto Sans Multani",
    "Noto Sans Myanmar",
    "Noto Sans Nabataean",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans NKo",
    "Noto Sans Ogham",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old Italic",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Oriya",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Runic",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Shavian",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Symbols",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Serif",
    "Noto Serif Ahom",
    "Noto Serif Balinese",
    "Noto Serif CJK JP",
    "Noto Serif CJK KR",
    "Noto Serif CJK SC",
    "Noto Serif CJK TC",
    "Noto Serif Myanmar",
    "NotoNaskhArabic",
    "NotoNaskhArabicUI",
    "NotoSansBengali",
    "NotoSansBengaliUI",
    "NotoSansCJK JP",
    "NotoSansCJK KR",
    "NotoSansCJK SC",
    "NotoSansCJK TC",
    "NotoSansDevanagari",
    "NotoSansDevanagariUI",
    "NotoSansGujarati",
    "NotoSansGujaratiUI",
    "NotoSansGurmukhi",
    "NotoSansGurmukhiUI",
    "NotoSansHebrew",
    "NotoSansKannada",
    "NotoSansKannadaUI",
    "NotoSansKhmer",
    "NotoSansKhmerUI",
    "NotoSansLao",
    "NotoSansLaoUI",
    "NotoSansMalayalam",
    "NotoSansMalayalamUI",
    "NotoSansMyanmar",
    "NotoSansMyanmarUI",
    "NotoSansTamil",
    "NotoSansTamilUI",
    "NotoSansTelugu",
    "NotoSansTeluguUI",
    "NotoSansThai",
    "NotoSansThaiUI",
    "NotoSerifBengali",
    "NotoSerifCJK JP",
    "NotoSerifCJK KR",
    "NotoSerifCJK SC",
    "NotoSerifCJK TC",
    "NotoSerifDevanagari",
    "NotoSerifGujarati",
    "NotoSerifGurmukhi",
    "NotoSerifHebrew",
    "NotoSerifKannada",
    "NotoSerifKhmer",
    "NotoSerifLao",
    "NotoSerifMalayalam",
    "NotoSerifMyanmar",
    "NotoSerifTamil",
    "NotoSerifTelugu",
    "NotoSerifThai",
    "NTR",
    "Old English Text MT",
    "Onyx",
    "Optima",
    "ori1Uni",
    "Oriya MN",
    "Oriya Sangam MN",
    "P052",
    "Padauk",
    "Padauk Book",
    "padmaa",
    "padmaa-Bold.1.1",
    "padmmaa",
    "Pagul",
    "Palace Script MT",
    "Palatino",
    "palatino",
    "Papyrus",
    "Papyrus Condensed",
    "Parchment",
    "Party LET",
    "Peddana",
    "Perpetua",
    "Perpetua Titling MT",
    "Phetsarath OT",
    "Phosphate",
    "PingFang HK",
    "PingFang SC",
    "PingFang TC",
    "Plantagenet Cherokee",
    "Playbill",
    "Poor Richard",
    "Pothana2000",
    "Pristina",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Purisa",
    "Raanana",
    "Rachana",
    "RaghuMalayalamSans",
    "Ramabhadra",
    "Ramaraja",
    "Rasa",
    "Rasa Light",
    "Rasa Medium",
    "Rasa SemiBold",
    "Ravie",
    "Rekha",
    "Roboto",
    "roboto-flex",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Roman Regular",
    "Saab",
    "Sahadeva",
    "Samanata",
    "Samyak Devanagari",
    "Samyak Gujarati",
    "Samyak Malayalam",
    "Samyak Tamil",
    "Sana",
    "sans-serif",
    "sans-serif-black",
    "sans-serif-condensed",
    "sans-serif-condensed-light",
    "sans-serif-condensed-medium",
    "sans-serif-light",
    "sans-serif-medium",
    "sans-serif-monospace",
    "sans-serif-smallcaps",
    "sans-serif-thin",
    "Sarai",
    "Sathu",
    "Savoye LET",
    "Sawasdee",
    "Script",
    "Script Regular",
    "SCRIPTINA",
    "Seravek",
    "Seravek ExtraLight",
    "Seravek Light",
    "Seravek Medium",
    "serif",
    "serif-bold",
    "serif-monospace",
    "Serifa",
    "SF Arabic",
    "SF Arabic Rounded",
    "SF Armenian",
    "SF Compact",
    "SF Compact Rounded",
    "SF Georgian",
    "SF Hebrew",
    "SF Mono",
    "SF Pro",
    "SF Pro Rounded",
    "Showcard Gothic",
    "Shree Devanagari 714",
    "Shree Devanagari 714 Bold",
    "Shree Devanagari 714 Bold Italic",
    "Shree Devanagari 714 Italic",
    "SignPainter",
    "SignPainter-HouseScript",
    "Silom",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Skia",
    "Small Fonts",
    "Small Fonts Regular",
    "Snap ITC",
    "Snell Roundhand",
    "Songti SC",
    "Songti TC",
    "source-sans-pro",
    "source-sans-pro-semi-bold",
    "Sree Krushnadevaraya",
    "Staccato222 BT",
    "Standard Symbols PS",
    "Stencil",
    "STFangsong",
    "STFangSong",
    "STIXGeneral",
    "STIXGeneral-Bold",
    "STIXGeneral-BoldItalic",
    "STIXGeneral-Italic",
    "STIXGeneral-Regular",
    "STIXIntegralsD",
    "STIXIntegralsD-Bold",
    "STIXIntegralsD-Regular",
    "STIXIntegralsSm",
    "STIXIntegralsSm-Bold",
    "STIXIntegralsSm-Regular",
    "STIXIntegralsUp",
    "STIXIntegralsUp-Bold",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsUpD",
    "STIXIntegralsUpD-Bold",
    "STIXIntegralsUpD-Regular",
    "STIXIntegralsUpSm",
    "STIXIntegralsUpSm-Bold",
    "STIXIntegralsUpSm-Regular",
    "STIXNonUnicode",
    "STIXNonUnicode-Bold",
    "STIXNonUnicode-BoldItalic",
    "STIXNonUnicode-Italic",
    "STIXNonUnicode-Regular",
    "STIXSizeFiveSym",
    "STIXSizeFiveSym-Regular",
    "STIXSizeFourSym",
    "STIXSizeFourSym-Bold",
    "STIXSizeFourSym-Regular",
    "STIXSizeOneSym",
    "STIXSizeOneSym-Bold",
    "STIXSizeOneSym-Regular",
    "STIXSizeThreeSym",
    "STIXSizeThreeSym-Bold",
    "STIXSizeThreeSym-Regular",
    "STIXSizeTwoSym",
    "STIXSizeTwoSym-Bold",
    "STIXSizeTwoSym-Regular",
    "STIXVariants",
    "STIXVariants-Bold",
    "STIXVariants-Regular",
    "STKaiti",
    "STSong",
    "STXihei",
    "Sukhumvit Set",
    "Superclarendon",
    "Suranna",
    "Suravaram",
    "Suruma",
    "Sylfaen",
    "Sylfaen Regular",
    "Symbol",
    "Symbol Regular",
    "System",
    "System Bold",
    "system-ui",
    "tahoma",
    "Tamil MN",
    "Tamil Sangam MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "Tempus Sans ITC",
    "Thonburi",
    "Tibetan Machine Uni",
    "Times",
    "times",
    "Times LT MM",
    "Times New Roman",
    "times new roman",
    "Timmana",
    "TRAJAN PRO",
    "Trattatello",
    "Trebuchet MS",
    "TTCommons",
    "Tw Cen MT",
    "Tw Cen MT Condensed",
    "ui-monospace",
    "ui-rounded",
    "ui-sans-serif",
    "ui-serif",
    "Umpush",
    "Uroob",
    "utkal",
    "Vemana2000",
    "Verdana",
    "verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Vrinda",
    "Waree",
    "Waseem",
    "Wide Latin",
    "Yrsa",
    "Yrsa Light",
    "Yrsa Medium",
    "Yrsa SemiBold",
    "Z003",
    "Zapf Dingbats",
    "Zapfino",
    "ZWAdobeF",
];
