export const queryKeys = {
	groups: ['groups'] as const,
	profiles: ['profiles'] as const,
	profileRuntimeDetails: (profileId: string | null) => ['profile-runtime-details', profileId] as const,
	proxies: ['proxies'] as const,
	resources: ['resources'] as const,
	devicePresets: ['device-presets'] as const,
	devicePresetRefCount: (presetId: string) => ['device-preset-ref-count', presetId] as const,
	windowStates: ['window-states'] as const,
	syncTargets: ['sync-targets'] as const,
	displayMonitors: ['display-monitors'] as const,
	profileProxyBindings: (profileIds: string[]) => ['profile-proxy-bindings', ...profileIds] as const,
	automationScripts: ['automation-scripts'] as const,
	automationRuns: (scriptId: string) => ['automation-runs', scriptId] as const,
	aiConfigs: ['ai-configs'] as const,
	defaultAiConfig: ['default-ai-config'] as const,
	chatSessions: ['chat-sessions'] as const,
	chatMessages: (sessionId: string) => ['chat-messages', sessionId] as const,
	aiSkills: ['ai-skills'] as const,
	aiSkill: (slug: string) => ['ai-skills', slug] as const,
	fsRoots: ['fs-roots'] as const,
	fsDir: (rootId: string, relPath: string) => ['fs-dir', rootId, relPath] as const,
	mcpServers: ['mcp-servers'] as const,
	mcpServer: (id: string) => ['mcp-servers', id] as const,
	mcpTools: (serverId: string) => ['mcp-tools', serverId] as const,
	chromiumVersions: {
		byPlatform: (platform: string) => ['chromium-versions', platform] as const,
	},
	bookmarks: {
		byProfile: (profileId: string) => ['bookmarks', 'by-profile', profileId] as const,
		templates: ['bookmark-templates'] as const,
		subscriptionsByTemplate: (templateId: number) =>
			['bookmark-subscriptions', 'by-template', templateId] as const,
		subscriptionsByProfile: (profileId: string) =>
			['bookmark-subscriptions', 'by-profile', profileId] as const,
	},
};
